name: Build, Test and Deploy in QA

on:
  push:
    branches:
      - qa

jobs:
  Test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm i --save --legacy-peer-deps --force
      - name: Generate Prisma Clients
        run: npm run generate:postgres & npm run generate:mongo
      - name: Run tests
        run: npm run test:cov
      - name: Verify Code Coverage
        uses: themichaelhall/check-code-coverage@v1
        with:
          report: ./coverage/clover.xml
          required-percentage: 80
  Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Docker Login - Container Registry
        uses: Azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag cybergenios/cybergenios-api-v2-qa:${{github.run_number}}

      - name: Publish Docker image into Repository
        run: docker push cybergenios/cybergenios-api-v2-qa:${{github.run_number}}

      - name: Set latest tag
        run: docker tag cybergenios/cybergenios-api-v2-qa:${{github.run_number}} cybergenios/cybergenios-api-v2-qa:latest

      - name: Publish Docker latest image into Repository
        run: docker push cybergenios/cybergenios-api-v2-qa:latest

      - name: Invoke deploy qa workflow with inputs
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Deploy to QA
          repo: Cyber-Genios/cybergenios-api-infra-qa
          token: ${{ secrets.GIT_TOKEN }}
          ref: 'refs/heads/master'
          inputs: '{ "tag": "${{ github.run_number }}" }'
